import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import {
  ClerkProvider,
} from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col mx-auto md:w-[95%] lg:w-[90%]">
          <Navbar />
          <div className="flex-1 h-full">
          {children}
          </div>
        </div>
      </body>
    </html>
    </ClerkProvider>
  );
}
